#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiTracNghiem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TRACNGHIEM")]
	public partial class DBAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGIAOVIEN_DANGKY(GIAOVIEN_DANGKY instance);
    partial void UpdateGIAOVIEN_DANGKY(GIAOVIEN_DANGKY instance);
    partial void DeleteGIAOVIEN_DANGKY(GIAOVIEN_DANGKY instance);
    partial void InsertBANGDIEM(BANGDIEM instance);
    partial void UpdateBANGDIEM(BANGDIEM instance);
    partial void DeleteBANGDIEM(BANGDIEM instance);
    #endregion
		
		public DBAppDataContext() : 
				base(global::ThiTracNghiem.Properties.Settings.Default.TRACNGHIEMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GIAOVIEN_DANGKY> GIAOVIEN_DANGKies
		{
			get
			{
				return this.GetTable<GIAOVIEN_DANGKY>();
			}
		}
		
		public System.Data.Linq.Table<BANGDIEM> BANGDIEMs
		{
			get
			{
				return this.GetTable<BANGDIEM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAOVIEN_DANGKY")]
	public partial class GIAOVIEN_DANGKY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAGV;
		
		private string _MAMH;
		
		private string _MALOP;
		
		private System.Nullable<char> _TRINHDO;
		
		private System.Nullable<System.DateTime> _NGAYTHI;
		
		private short _LAN;
		
		private System.Nullable<short> _SOCAUTHI;
		
		private System.Nullable<short> _THOIGIAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGVChanging(string value);
    partial void OnMAGVChanged();
    partial void OnMAMHChanging(string value);
    partial void OnMAMHChanged();
    partial void OnMALOPChanging(string value);
    partial void OnMALOPChanged();
    partial void OnTRINHDOChanging(System.Nullable<char> value);
    partial void OnTRINHDOChanged();
    partial void OnNGAYTHIChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHIChanged();
    partial void OnLANChanging(short value);
    partial void OnLANChanged();
    partial void OnSOCAUTHIChanging(System.Nullable<short> value);
    partial void OnSOCAUTHIChanged();
    partial void OnTHOIGIANChanging(System.Nullable<short> value);
    partial void OnTHOIGIANChanged();
    #endregion
		
		public GIAOVIEN_DANGKY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGV", DbType="Char(8)")]
		public string MAGV
		{
			get
			{
				return this._MAGV;
			}
			set
			{
				if ((this._MAGV != value))
				{
					this.OnMAGVChanging(value);
					this.SendPropertyChanging();
					this._MAGV = value;
					this.SendPropertyChanged("MAGV");
					this.OnMAGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMH
		{
			get
			{
				return this._MAMH;
			}
			set
			{
				if ((this._MAMH != value))
				{
					this.OnMAMHChanging(value);
					this.SendPropertyChanging();
					this._MAMH = value;
					this.SendPropertyChanged("MAMH");
					this.OnMAMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDO", DbType="Char(1)")]
		public System.Nullable<char> TRINHDO
		{
			get
			{
				return this._TRINHDO;
			}
			set
			{
				if ((this._TRINHDO != value))
				{
					this.OnTRINHDOChanging(value);
					this.SendPropertyChanging();
					this._TRINHDO = value;
					this.SendPropertyChanged("TRINHDO");
					this.OnTRINHDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTHI
		{
			get
			{
				return this._NGAYTHI;
			}
			set
			{
				if ((this._NGAYTHI != value))
				{
					this.OnNGAYTHIChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHI = value;
					this.SendPropertyChanged("NGAYTHI");
					this.OnNGAYTHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAN", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short LAN
		{
			get
			{
				return this._LAN;
			}
			set
			{
				if ((this._LAN != value))
				{
					this.OnLANChanging(value);
					this.SendPropertyChanging();
					this._LAN = value;
					this.SendPropertyChanged("LAN");
					this.OnLANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCAUTHI", DbType="SmallInt")]
		public System.Nullable<short> SOCAUTHI
		{
			get
			{
				return this._SOCAUTHI;
			}
			set
			{
				if ((this._SOCAUTHI != value))
				{
					this.OnSOCAUTHIChanging(value);
					this.SendPropertyChanging();
					this._SOCAUTHI = value;
					this.SendPropertyChanged("SOCAUTHI");
					this.OnSOCAUTHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN", DbType="SmallInt")]
		public System.Nullable<short> THOIGIAN
		{
			get
			{
				return this._THOIGIAN;
			}
			set
			{
				if ((this._THOIGIAN != value))
				{
					this.OnTHOIGIANChanging(value);
					this.SendPropertyChanging();
					this._THOIGIAN = value;
					this.SendPropertyChanged("THOIGIAN");
					this.OnTHOIGIANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGDIEM")]
	public partial class BANGDIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASV;
		
		private string _MAMH;
		
		private short _LAN;
		
		private System.Nullable<System.DateTime> _NGAYTHI;
		
		private System.Nullable<double> _DIEM;
		
		private string _BAITHI;
		
		private System.Guid _rowguid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASVChanging(string value);
    partial void OnMASVChanged();
    partial void OnMAMHChanging(string value);
    partial void OnMAMHChanged();
    partial void OnLANChanging(short value);
    partial void OnLANChanged();
    partial void OnNGAYTHIChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHIChanged();
    partial void OnDIEMChanging(System.Nullable<double> value);
    partial void OnDIEMChanged();
    partial void OnBAITHIChanging(string value);
    partial void OnBAITHIChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public BANGDIEM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASV", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASV
		{
			get
			{
				return this._MASV;
			}
			set
			{
				if ((this._MASV != value))
				{
					this.OnMASVChanging(value);
					this.SendPropertyChanging();
					this._MASV = value;
					this.SendPropertyChanged("MASV");
					this.OnMASVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMH
		{
			get
			{
				return this._MAMH;
			}
			set
			{
				if ((this._MAMH != value))
				{
					this.OnMAMHChanging(value);
					this.SendPropertyChanging();
					this._MAMH = value;
					this.SendPropertyChanged("MAMH");
					this.OnMAMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAN", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short LAN
		{
			get
			{
				return this._LAN;
			}
			set
			{
				if ((this._LAN != value))
				{
					this.OnLANChanging(value);
					this.SendPropertyChanging();
					this._LAN = value;
					this.SendPropertyChanged("LAN");
					this.OnLANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTHI
		{
			get
			{
				return this._NGAYTHI;
			}
			set
			{
				if ((this._NGAYTHI != value))
				{
					this.OnNGAYTHIChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHI = value;
					this.SendPropertyChanged("NGAYTHI");
					this.OnNGAYTHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM", DbType="Float")]
		public System.Nullable<double> DIEM
		{
			get
			{
				return this._DIEM;
			}
			set
			{
				if ((this._DIEM != value))
				{
					this.OnDIEMChanging(value);
					this.SendPropertyChanging();
					this._DIEM = value;
					this.SendPropertyChanged("DIEM");
					this.OnDIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAITHI", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string BAITHI
		{
			get
			{
				return this._BAITHI;
			}
			set
			{
				if ((this._BAITHI != value))
				{
					this.OnBAITHIChanging(value);
					this.SendPropertyChanging();
					this._BAITHI = value;
					this.SendPropertyChanged("BAITHI");
					this.OnBAITHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
